# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-added-large-files
        exclude: ^docs/
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-symlinks
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.31.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        exclude: ^docs/
        types: [file]
        additional_dependencies:
          - eslint@9.31.0
          - eslint-config-prettier@10.1.8
          - "@typescript-eslint/eslint-plugin@8.38.0"
          - "@typescript-eslint/parser@8.38.0"
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(yml|yaml|json|ts|js|mjs|cjs)$
        stages: [pre-commit]
